name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file and fill it with DATABASE_URL
        run: echo "DATABASE_URL=postgresql://shop_admin:111111@db:5432/shop_db" > .env

      - name: Setup Docker network
        run: |
          docker network create api_container || echo "Network already exists"

      - name: Run PostgreSQL container
        run: |
          docker run --name db --network api_container -e POSTGRES_DB=shop_db -e POSTGRES_USER=shop_admin -e POSTGRES_PASSWORD=111111 -v pgdata:/var/lib/postgresql/data_db_container postgres:latest &

      - name: Build and run the first API container
        run: |
          docker build -t shop_api_good -f DockerFileGood .
          docker run --name shop_api_good_container --network api_container -p 8080:8000 -v shop_api_volume:/api_data shop_api_good &

      - name: Build and run the second API container
        run: |
          docker build -t shop_api_bad -f DockerFileBad .
          docker run --name shop_api_bad_container --network api_container -p 8000:8000 -v shop_api_volume:/api_data shop_api_bad &

      - name: Check if API is reachable
        run: |
          curl -f http://localhost:8080/docs || exit 1 
          curl -f http://localhost:8000/docs || exit 1