name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file and fill it with DATABASE_URL
        run: |
          echo "DATABASE_URL=postgresql://shop_admin:111111@db:5432/shop_db" > .env
          echo "POSTGRES_DB=shop_db" >> .env
          echo "POSTGRES_USER=shop_admin" >> .env
          echo "POSTGRES_PASSWORD=111111" >> .env

      - name: Setup Docker network
        run: |
          docker network create api_container || echo "Network already exists"

      - name: Run PostgreSQL container
        run: |
          docker run --name db --network api_container -e POSTGRES_DB=shop_db -e POSTGRES_USER=shop_admin -e POSTGRES_PASSWORD=111111 -v pgdata:/var/lib/postgresql/data_db_container postgres:latest &

      - name: Build and run good container API
        run: |
          docker build -t shop_api_good -f docker/DockerFileGood .
          docker run --name shop_api_good_container --network api_container -p 8080:8000 -v shop_api_volume:/api_data shop_api_good &

      - name: Build and run bad container API
        run: |
          docker build -t shop_api_bad -f docker/DockerFileBad .
          docker run --name shop_api_bad_container --network api_container -p 8081:8000 -v shop_api_volume:/api_data shop_api_bad &

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose -p containerscourse --env-file .env -f docker/docker-compose.yml up -d

      - name: Check if API is reachable
        run: |
          curl -f http://localhost:8080/docs || exit 1 
          curl -f http://localhost:8081/docs || exit 1
          curl -f http://localhost:8000/docs || exit 1
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:9090 || exit 1